from situacao import Situacao
from tipotemperatura import TipoTemperatura
from receita import Receita
from origem import Origem
from questao import Questao
from oportunidade import Oportunidade
from historico import Historico
from resposta import Resposta
from historicoresposta import HistoricoResposta
from rtc import Rtc